network:
  port: 5000
  sndbuf: 131072
  watermarks:
    high: 131072
    low: 65536
strategy:
  sync:
    limits:
      packets: 10
      size: 131072
      time: 200
streaming:
  file:
    class: me.vzhilin.mediaserver.media.impl.file.FileMediaPacketSource
    conf:
      basedir: /home/vzhilin/misc/video_samples/
      file: simpsons_video.mkv
  picture:
    class: me.vzhilin.mediaserver.media.impl.picture.SimplePictureSource
    conf:
      picture:
        width: 640
        height: 480
      encoder:
        bitrate: 400000
        fps: 25
        gop_size: 10
        max_b_frames: 1