network:
  port: 5000
  sndbuf: 64000
  watermarks:
    high: 524288
    low: 262144
source:
  file:
    dir: /home/vzhilin/misc/video_samples/
  picture:
    width: 640
    height: 480
    encoder:
      bitrate: 400000
      fps: 25
      gop_size: 10
      max_b_frames: 1
strategy:
  sync:
    limits:
      packets: 5
      size: 256000
      time: 200