network:
  port: 5000
  sndbuf: 256000
  watermarks:
    high: 128000
    low: 64000
strategy:
  sync:
    limits:
      packets: 1
      size: 256000
      time: 200
source:
  file:
    dir: /home/vzhilin/misc/video_samples/
  picture:
    width: 640
    height: 480
    encoder:
      bitrate: 400000
      fps: 25
      gop_size: 10
      max_b_frames: 1
